In [1]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[0])
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(b[0
])

1
[1 2 3 4]


In [10]:
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype) # object describing type of element in the array
print(b.itemsize) # the size in bytes of each element of the array
print(b.data) # the buffer containing the actual elements of the array

2
(3, 4)
12
int32
4


In [15]:
a = np.arange(15).reshape(3,5) # 3 rows, 5 col
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


## 1D array, 2D array, ndarray, vector, matrix

In [18]:
print(np.zeros(5))
print(np.ones(3))
empty_array = np.empty(5)
print(empty_array)

[0. 0. 0. 0. 0.]
[1. 1. 1.]
[0. 0. 0. 0. 0.]


# NUMPY W3SCHOOL

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
# Checking NumPy Version
print(np.__version__)

1.20.3


## Creating Arrays

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [5]:
arr = np.array((1,2,3,4,5,6))
print(arr)

[1 2 3 4 5 6]


### Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays). nested array: are arrays that have arrays as their elements.

In [80]:
a = np.array(23) # 0d array
print(a)
b = np.array([1,2,3,4,5]) # 1d array
print(b)
c = np.array([[1,2,3], [4,5,6]]) # 2d array
print(c)
d = np.array([[[1,2,3], [4,5,6], [7, 8, 9]]]) # 3d array
print(d)

23
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [81]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [82]:
# Higher Dimensional Arrays
arr = np.array([1,2,3,4,5], ndmin= 5)
print(arr)
print('number of dimensions: ', arr.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimensions:  5


### Array Indexing

In [84]:
# Access Array Elements
arr = np.array([1,2,3,4,5])
print(arr[0]) # first element
print(arr[1]) # second element

1
2


In [85]:
# Get third and fourth element and add them
arr = np.array([1,2,3,4,5])
print(arr[2] + arr[3])

7


### Access 2d Array

In [89]:
arr = np.array([[1,2,3, 4, 5], [6,7,8,9,10]])
print(arr)
print("2nd element on 1st row: ", arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st row:  2
5th element on 2nd row:  10


### Access 3d Array

# NumPy QuickStart

In [20]:
arr = np.array([1,2,1])
print(arr.ndim) # number of axes (dimensions) of the array
print(arr.size) # total number of elements of the array
print(arr.shape) # dim of array: tuple of integers indicating the size of array in each dimension.
print(arr.dtype) # type of element in the array
print(arr.itemsize) # size of bytes of each element of the array. eg: float64 has itemsize 8 (64/8)
print(arr.data) # buffer containing actual elements of the array. (we don't normally need to use this)

1
3
(3,)
int32
4


In [28]:
a = np.arange(15).reshape(3,5)
print(a)
print(a.shape) # dimension
print(a.ndim) # no of axis
print(a.dtype.name) 
print(a.itemsize)
print(a.size) # total no of elements
print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
2
int32
4
15
<class 'numpy.ndarray'>


## Array Creation

we can create an array from a regular Python list or tuple using array(). type of resulting array is deduced from the type of the elements in the sequences.

In [29]:
a = np.array([2,3,4,5])
print(a)
print(a.dtype)
b = np.array((1.2, 2.4, 3.6))
print(b)
print(b.dtype)

[2 3 4 5]
int32
[1.2 2.4 3.6]
float64


array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [33]:
a = np.array([[1.3, 2, 3], [4,5,6]])
print(a)

[[1.3 2.  3. ]
 [4.  5.  6. ]]


The type of the array can also be explicitly specified at creation time:

In [34]:
b = np.array([[1, 2], [3, 4]], dtype=complex)
print(b)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


Often the elements of array are originally unknown, but it's size are known. To create array with initial placeholders we use:

zeroes

ones

empty

In [47]:
np.zeros((3,4)) # default dtype is float64

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
a = np.ones((2,3,4), dtype= np.int8)
print(a)
print(a.ndim)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
3


In [48]:
np.empty((2,3)) # inserts random number

array([[1.3, 2. , 3. ],
       [4. , 5. , 6. ]])

To create sequence of numbers, we use arange()

In [51]:
np.arange(10,30, 5) # (inclusive, exclusive, steps)

array([10, 15, 20, 25])

In [52]:
np.arange(0, 2, 0.3) # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

it is generally not possible to predict the number of elemenets obtained, due to finite floating point precision. For this reason, it is usually better to use the function linespace() that receives as an argument the number of elements that we want instead of step:

In [53]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [60]:
from numpy import pi
x = np.linspace(0, 2*pi, 100) # useful to evaluate function at lots of points
f = np.sin(x)

## Printing arrays

In [62]:
a = np.arange(6) # 1d array
print(a)

[0 1 2 3 4 5]


In [63]:
b = np.arange(12).reshape(4,3) # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [65]:
c = np.arange(24).reshape(2, 3, 4) # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


If array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners. 

In [66]:
print(np.arange(100000))

[    0     1     2 ... 99997 99998 99999]


In [67]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


To disable this behavior and force NumPy to print the entire array, we can change the printing options using set_printoptions()

In [69]:
import sys
np.set_printoptions(threshold=sys.maxsize)

## Basic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [70]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [72]:
c = a-b 
print(c)

[20 29 38 47]


In [74]:
print(b**2)

[0 1 4 9]


In [75]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [79]:
a < 35 # returns boolean array

array([ True,  True, False, False])