Python Data Analytics Book

# Chapter 3 NumPy

In [1]:
import numpy as np

## Basic Operations

### Arithmetic Operations

In [2]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [3]:
a + 4 # operations are element-wise

array([4, 5, 6, 7])

In [4]:
a*2

array([0, 2, 4, 6])

In [5]:
b = np.arange(4,8)
print(b)

[4 5 6 7]


In [7]:
print(a+b)

[ 4  6  8 10]


In [8]:
print(a-b)

[-4 -4 -4 -4]


In [9]:
print(a*b)

[ 0  5 12 21]


these operations are also available for functions, provided that the value returned is a NumPy array. For example, we can multiply the array with the sine or the square root of the elements of the array b.

In [10]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [13]:
print(a*np.sqrt(b))

[0.         2.23606798 4.89897949 7.93725393]


Even in the multidimensional case, the arithmetic operations are element-wise. 

In [18]:
A = np.arange(0, 9).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
B = np.ones((3,3))
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
print(A*B)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


### The Matrix Product

We use dot() function to do the matrix multiplication.

In [21]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [22]:
# We can also write as follows
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

Since matrix product is not a commutative operation, then the order of operands is important. A*B is not equal to B*A.

In [23]:
B.dot(A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

### Increment and Decrement Operators

In [29]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [30]:
a+= 1
print(a)

[1 2 3 4]


In [31]:
a -= 2
print(a)

[-1  0  1  2]


In [32]:
a *= 2
print(a)

[-2  0  2  4]


### Universal Functions (ufunc)

Function operating of an array in an element-by-element fashion. This outputs an array of the same size of inputs.

eg: mathematical/trigonometric operations like sqrt(), log(), sin()

In [33]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

In [34]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [35]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [36]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Aggregate Functions

In [44]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.std())

15.0
0.3
5.7
3.0
2.0079840636817816


## Indexing, Slicing, and Iterating

### Indexing

In [46]:
a = np.arange(10, 16)
print(a)

[10 11 12 13 14 15]


In [47]:
a[4]

14

In [48]:
a[-1]

15

To select multiple items at once, we can pass array of indexes within square brackets. 

In [49]:
a[[2,3,5]]

array([12, 13, 15])