Python Data Analytics Book

# Chapter 3 NumPy

In [1]:
import numpy as np

## Arithmetic Operations

In [2]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [3]:
a + 4 # operations are element-wise

array([4, 5, 6, 7])

In [4]:
a*2

array([0, 2, 4, 6])

In [5]:
b = np.arange(4,8)
print(b)

[4 5 6 7]


In [7]:
print(a+b)

[ 4  6  8 10]


In [8]:
print(a-b)

[-4 -4 -4 -4]


In [9]:
print(a*b)

[ 0  5 12 21]


these operations are also available for functions, provided that the value returned is a NumPy array. For example, we can multiply the array with the sine or the square root of the elements of the array b.

In [10]:
a * np.sin(b)

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [13]:
print(a*np.sqrt(b))

[0.         2.23606798 4.89897949 7.93725393]


Even in the multidimensional case, the arithmetic operations are element-wise. 

In [18]:
A = np.arange(0, 9).reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
B = np.ones((3,3))
print(B)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
print(A*B)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


### The Matrix Product

We use dot() function to do the matrix multiplication.

In [21]:
np.dot(A,B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

In [22]:
# We can also write as follows
A.dot(B)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

Since matrix product is not a commutative operation, then the order of operands is important. A*B is not equal to B*A.

In [23]:
B.dot(A)

array([[ 9., 12., 15.],
       [ 9., 12., 15.],
       [ 9., 12., 15.]])

### Increment and Decrement Operators